export const SERVICES = [
  { id: 1, label: "Architecture" },
  { id: 2, label: "Bathroom Fitting" },
  { id: 3, label: "Bricklaying" },
  { id: 4, label: "CAD / Drawings" },
  { id: 5, label: "Carpentry" },
  { id: 6, label: "Carpets & Lino" },
  { id: 7, label: "Central Heating" },
  { id: 8, label: "Cleaning Services (domestic and commercial/office)" },
  { id: 9, label: "Conservatories" },
  { id: 10, label: "Conversions - General" },
  { id: 11, label: "Damp Proofing" },
  { id: 12, label: "Decking" },
  { id: 13, label: "Demolition" },
  { id: 14, label: "Driveways (Paved & Loose)" },
  { id: 15, label: "Driveways (Tarmac Surface)" },
  { id: 16, label: "Electrical" },
  { id: 17, label: "Extensions" },
  { id: 18, label: "Fascias & Soffits" },
  { id: 19, label: "Fencing" },
  { id: 20, label: "FeFireplaces & Fluesncing" },
  { id: 21, label: "Garden Maintenance" },
  { id: 22, label: "Gas Work" },
  { id: 23, label: "Groundwork & Foundations" },
  { id: 24, label: "Guttering" },
  { id: 25, label: "Handyman" },
  { id: 26, label: "Insulation" },
  { id: 27, label: "Joinery & Cabinet Making" },
  { id: 28, label: "Kitchen Fitting" },
  { id: 29, label: "Landscaping" },
  { id: 30, label: "Locksmiths" },
  { id: 31, label: "Loft Conversion" },
  { id: 32, label: "New Builds" },
  { id: 33, label: "Painting & Decorating" },
  { id: 34, label: "Plastering" },
  { id: 35, label: "Plumbing" },
  { id: 36, label: "Repointing" },
  { id: 37, label: "Restoration & Refurbishment" },
  { id: 38, label: "Roofing (Flat)" },
  { id: 39, label: "Roofing (Pitched)" },
  { id: 40, label: "Security Systems" },
  { id: 41, label: "Stonemasonry" },
  { id: 42, label: "Tiling" },
  { id: 43, label: "Tree Surgery" },
  { id: 44, label: "Waste Clearance" },
  { id: 45, label: "Windows & Doors (uPVC & Metal)" },
  { id: 46, label: "Windows & Doors (Wooden)" },
  { id: 47, label: "Windows & Door Repair" },
];
